// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerAddCommands(program: Command, client: OmniFocusClient) {
  const add = program.command("add").description("add commands");

  add
    .description("Add a new task.")
    .alias("add t")
    .alias("add task")
    .argument("<name>", "Task name")
    .option("-p, --project <string>", "Project name or ID")
    .option("-n, --note <string>", "Task note")
    .option("-d, --due <date>", "Due date")
    .option("--defer <date>", "Defer date")
    .option("-f, --flagged", "Mark as flagged")
    .option("-t, --tag <string>", "Primary tag")
    .option("--tags <string[]>", "Multiple tags (comma-sep)")
    .option("-e, --estimate <number>", "Estimated minutes")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.project !== undefined) clientArgs["project"] = options.project;
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.due) clientArgs["dueDate"] = parseCliDate(options.due);
      if (options.defer) clientArgs["deferDate"] = parseCliDate(options.defer);
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;
      if (options.tag !== undefined) clientArgs["tag"] = options.tag;
      if (options.tags !== undefined) clientArgs["tags"] = parseCsv(options.tags);
      if (options.estimate !== undefined) clientArgs["estimatedMinutes"] = parseInt(options.estimate, 10);

      
      const result = await (client as any).createTask(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task");
    });

  add.command("batch")
    .description("Create projects and tasks from an indented outline via stdin.")
    .alias("add b")
    .option("-f, --folder <string>", "Add to specific folder")
    .option("--sequential", "Make all projects sequential")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      
      if (process.stdin.isTTY) {
        console.error("Error: --stdin expected but no data provided via pipe.");
        process.exit(64);
      }
      const chunks = [];
      for await (const chunk of process.stdin) chunks.push(chunk);
      stdinData = Buffer.concat(chunks).toString();
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      

      // Map flags
      if (options.folder !== undefined) clientArgs["folder"] = options.folder;
      if (options.sequential !== undefined) clientArgs["sequential"] = options.sequential;

      
      const { parseOutline } = await import("../outline.js");
      const items = parseOutline(stdinData);
      const result = await client.batchCreateTasks({ tasks: items, ...clientArgs });
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });

  add.command("project")
    .description("Create a new project.")
    .alias("add p")
    .argument("<name>", "Project name")
    .option("-f, --folder <string>", "Add to specific folder (name or ID)")
    .option("-n, --note <string>", "Project note")
    .option("-d, --due <date>", "Due date")
    .option("--defer <date>", "Defer date")
    .option("--flagged", "Mark as flagged")
    .option("-t, --tag <string>", "Add primary tag")
    .option("--tags <string[]>", "Add multiple tags (comma-sep)")
    .option("--sequential", "Sequential project")
    .option("--parallel", "Parallel project")
    .option("--single-actions", "Single action list")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.folder !== undefined) clientArgs["folder"] = options.folder;
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.due) clientArgs["dueDate"] = parseCliDate(options.due);
      if (options.defer) clientArgs["deferDate"] = parseCliDate(options.defer);
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;
      if (options.tag !== undefined) clientArgs["tag"] = options.tag;
      if (options.tags !== undefined) clientArgs["tags"] = parseCsv(options.tags);
      if (options.sequential !== undefined) clientArgs["sequential"] = options.sequential;
      if (options.parallel !== undefined) clientArgs["sequential"] = false;
      if (options.singleActions !== undefined) clientArgs["singleActionList"] = options.singleActions;

      
      const result = await (client as any).createProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });
}
