// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerDropCommands(program: Command, client: OmniFocusClient) {

  program.command("drop")
    .description("Drop task(s).")
    .argument("<ids...>", "Task IDs")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["ids"] = positionalArgs[0];

      // Map flags
      

      
      const ids = clientArgs["ids"];
      const results = [];
      for (const id of ids) {
        const singleArgs = { ...clientArgs, id };
        delete (singleArgs as any)["ids"];
        results.push(await (client as any).dropTask(singleArgs));
      }
      const result = results.length === 1 ? results[0] : { success: true, message: `Processed ${results.length} items` };
      
      formatOutput(result, { ...program.opts(), ...options }, "message");
    });
}
