// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerFolderCommands(program: Command, client: OmniFocusClient) {
  const folder = program.command("folder").description("folder commands");

  folder.command("add")
    .description("Create a new folder.")
    .alias("folder create")
    .argument("<name>", "Folder name")
    .option("-p, --parent <string>", "Parent folder ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.parent !== undefined) clientArgs["parent"] = options.parent;

      
      const result = await (client as any).createFolder(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "folder");
    });

  folder.command("modify")
    .description("Modify an existing folder.")
    .alias("folder mod")
    .argument("<id>", "Folder ID")
    .option("--name <string>", "Rename folder")
    .option("--note <string>", "Set folder note")
    .option("--hidden", "Hide folder")
    .option("--visible", "Show folder")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      if (options.name !== undefined) clientArgs["name"] = options.name;
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.hidden !== undefined) clientArgs["hidden"] = options.hidden;
      if (options.visible !== undefined) clientArgs["visible"] = options.visible;

      
      const result = await (client as any).updateFolder(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "folder");
    });
}
