// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerGetCommands(program: Command, client: OmniFocusClient) {
  const get = program.command("get").description("get commands");

  get.command("task")
    .description("Get detailed information about a task.")
    .alias("get t")
    .argument("<id>", "Task ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).getTask(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task");
    });

  get.command("project")
    .description("Get detailed information about a project.")
    .alias("get p")
    .argument("<idOrName>", "Project name or ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["idOrName"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).getProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  get.command("project-tasks")
    .description("List tasks in a project.")
    .alias("get pt")
    .argument("<projectId>", "Project ID")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-a, --all", "Include completed tasks")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["projectId"] = positionalArgs[0];

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;

      
      const result = await (client as any).getProjectTasks(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });
}
