// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { registerSummaryCommands } from "./summary.js";
import { registerListCommands } from "./list.js";
import { registerSearchCommands } from "./search.js";
import { registerTagCommands } from "./tag.js";
import { registerAddCommands } from "./add.js";
import { registerQuickCommands } from "./quick.js";
import { registerModifyCommands } from "./modify.js";
import { registerFlagCommands } from "./flag.js";
import { registerUnflagCommands } from "./unflag.js";
import { registerCompleteCommands } from "./complete.js";
import { registerDropCommands } from "./drop.js";
import { registerDeleteCommands } from "./delete.js";
import { registerReorderCommands } from "./reorder.js";
import { registerProjectCommands } from "./project.js";
import { registerMoveCommands } from "./move.js";
import { registerFolderCommands } from "./folder.js";
import { registerSyncCommands } from "./sync.js";
import { registerReviewCommands } from "./review.js";
import { registerGetCommands } from "./get.js";
import { registerPerspectivesCommands } from "./perspectives.js";
import { registerQeCommands } from "./qe.js";

export function registerAllCommands(program: Command, client: OmniFocusClient) {
  registerSummaryCommands(program, client);
  registerListCommands(program, client);
  registerSearchCommands(program, client);
  registerTagCommands(program, client);
  registerAddCommands(program, client);
  registerQuickCommands(program, client);
  registerModifyCommands(program, client);
  registerFlagCommands(program, client);
  registerUnflagCommands(program, client);
  registerCompleteCommands(program, client);
  registerDropCommands(program, client);
  registerDeleteCommands(program, client);
  registerReorderCommands(program, client);
  registerProjectCommands(program, client);
  registerMoveCommands(program, client);
  registerFolderCommands(program, client);
  registerSyncCommands(program, client);
  registerReviewCommands(program, client);
  registerGetCommands(program, client);
  registerPerspectivesCommands(program, client);
  registerQeCommands(program, client);
}
