// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerListCommands(program: Command, client: OmniFocusClient) {
  const list = program.command("list").description("list commands");

  list.command("inbox")
    .description("List tasks in the Inbox.")
    .alias("ls i")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-a, --all", "Include completed")
    .option("--brief", "Brief output", true)
    .option("--full", "Full output")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{"inbox":true} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;
      if (options.brief !== undefined) clientArgs["brief"] = options.brief;
      if (options.full !== undefined) clientArgs["full"] = options.full;

      
      const result = await (client as any).listTasks(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });

  list.command("today")
    .description("List tasks due or available today.")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("--flagged", "Include flagged")
    .option("--brief", "Brief output", true)
    .option("--full", "Full output")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{"dueBefore":"today","available":true} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;
      if (options.brief !== undefined) clientArgs["brief"] = options.brief;
      if (options.full !== undefined) clientArgs["full"] = options.full;

      
      const result = await (client as any).listTasks(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });

  list.command("flagged")
    .description("List all flagged tasks.")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-a, --all", "Include completed")
    .option("--brief", "Brief output", true)
    .option("--full", "Full output")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{"flagged":true} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;
      if (options.brief !== undefined) clientArgs["brief"] = options.brief;
      if (options.full !== undefined) clientArgs["full"] = options.full;

      
      const result = await (client as any).listTasks(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });

  list.command("forecast")
    .description("List tasks for upcoming days.")
    .option("-d, --days <number>", "Number of days to show", "7")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      if (options.days !== undefined) clientArgs["days"] = options.days;

      
      const result = await (client as any).getForecast(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "forecast");
    });

  list.command("projects")
    .description("List all active projects.")
    .alias("ls p")
    .option("-f, --folder <string>", "Filter by folder name or ID")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-a, --all", "Include completed/dropped/on-hold")
    .option("--on-hold", "Include on-hold projects")
    .option("--brief", "Brief output", true)
    .option("--full", "Full output")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      if (options.folder !== undefined) clientArgs["folder"] = options.folder;
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;
      if (options.onHold !== undefined) clientArgs["on-hold"] = options.onHold;
      if (options.brief !== undefined) clientArgs["brief"] = options.brief;
      if (options.full !== undefined) clientArgs["full"] = options.full;

      
      const result = await (client as any).listProjects(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project[]");
    });

  list.command("folders")
    .description("List folder hierarchy.")
    .alias("ls f")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-f, --folder <string>", "List subfolders within this folder")
    .option("-r, --root-only", "Only show top-level folders")
    .option("--hidden", "Include hidden folders")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.folder !== undefined) clientArgs["folder"] = options.folder;
      if (options.rootOnly !== undefined) clientArgs["root-only"] = options.rootOnly;
      if (options.hidden !== undefined) clientArgs["hidden"] = options.hidden;

      
      const result = await (client as any).listFolders(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "folder[]");
    });

  list.command("tags")
    .description("List all tags.")
    .alias("ls t")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("--hidden", "Include hidden tags")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.hidden !== undefined) clientArgs["hidden"] = options.hidden;

      
      const result = await (client as any).listTags(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "tag[]");
    });
}
