// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerModifyCommands(program: Command, client: OmniFocusClient) {

  program.command("modify")
    .description("Update an existing task.")
    .alias("mod")
    .argument("<id>", "Task ID")
    .option("--name <string>", "Set task name")
    .option("-n, --note <string>", "Set task note")
    .option("-d, --due <date>", "Set due date")
    .option("--due-by <string>", "Adjust due date relatively (+3d, -1w)")
    .option("--defer <date>", "Set defer date")
    .option("--defer-by <string>", "Adjust defer date relatively")
    .option("-f, --flag", "Set flagged")
    .option("--unflag", "Remove flag")
    .option("-t, --tag <string>", "Set primary tag")
    .option("-p, --project <string>", "Move to project")
    .option("-e, --estimate <number>", "Set estimated minutes")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      if (options.name !== undefined) clientArgs["name"] = options.name;
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.due) clientArgs["due"] = parseCliDate(options.due);
      if (options.dueBy !== undefined) clientArgs["due-by"] = options.dueBy;
      if (options.defer) clientArgs["defer"] = parseCliDate(options.defer);
      if (options.deferBy !== undefined) clientArgs["defer-by"] = options.deferBy;
      if (options.flag !== undefined) clientArgs["flag"] = options.flag;
      if (options.unflag !== undefined) clientArgs["unflag"] = options.unflag;
      if (options.tag !== undefined) clientArgs["tag"] = options.tag;
      if (options.project !== undefined) clientArgs["project"] = options.project;
      if (options.estimate !== undefined) clientArgs["estimate"] = options.estimate;

      
      const result = await (client as any).updateTask(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task");
    });
}
