// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerMoveCommands(program: Command, client: OmniFocusClient) {

  program.command("move")
    .description("Move a project to a different folder.")
    .argument("<projectId>", "Project ID")
    .option("-f, --folder <string>", "Target folder (omit for root)")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["projectId"] = positionalArgs[0];

      // Map flags
      if (options.folder !== undefined) clientArgs["folder"] = options.folder;

      
      const result = await (client as any).moveProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });
}
