// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerNotifyCommands(program: Command, client: OmniFocusClient) {
  const notify = program.command("notify").description("notify commands");

  notify.command("list")
    .description("List the notifications (alarms) on a task.")
    .alias("ls")
    .argument("<taskId>", "Task ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["taskId"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).listTaskNotifications(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "notification[]");
    });

  notify.command("add")
    .description("Add a notification (alarm) to a task: at a fixed time, or relative to its due date.")
    .argument("<taskId>", "Task ID")
    .option("--at <date>", "Fire at a fixed time: 'YYYY-MM-DD HH:MM' (local), ISO 8601 with timezone, or +Nd/+Nw")
    .option("--before-due <string>", "Fire this long before the due date (15m, 1h30m, 2d, 1w)")
    .option("--after-due <string>", "Fire this long after the due date")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["taskId"] = positionalArgs[0];

      // Map flags
      if (options.at) clientArgs["absoluteDate"] = parseCliDate(options.at);
      if (options.beforeDue !== undefined) clientArgs["beforeDue"] = options.beforeDue;
      if (options.afterDue !== undefined) clientArgs["afterDue"] = options.afterDue;

      
      const result = await (client as any).addTaskNotification(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "notification");
    });

  notify.command("modify")
    .description("Change when a notification fires. Switching between a fixed time and a due-relative offset replaces the notification (new ID).")
    .alias("mod")
    .argument("<taskId>", "Task ID")
    .argument("<notificationId>", "Notification ID (from `of notify list`)")
    .option("--at <date>", "Fire at a fixed time: 'YYYY-MM-DD HH:MM' (local), ISO 8601 with timezone, or +Nd/+Nw")
    .option("--before-due <string>", "Fire this long before the due date (15m, 1h30m, 2d, 1w)")
    .option("--after-due <string>", "Fire this long after the due date")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["taskId"] = positionalArgs[0];
      clientArgs["notificationId"] = positionalArgs[1];

      // Map flags
      if (options.at) clientArgs["absoluteDate"] = parseCliDate(options.at);
      if (options.beforeDue !== undefined) clientArgs["beforeDue"] = options.beforeDue;
      if (options.afterDue !== undefined) clientArgs["afterDue"] = options.afterDue;

      
      const result = await (client as any).updateTaskNotification(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "notification");
    });

  notify.command("remove")
    .description("Remove a notification from a task.")
    .alias("rm")
    .argument("<taskId>", "Task ID")
    .argument("<notificationId>", "Notification ID (from `of notify list`)")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["taskId"] = positionalArgs[0];
      clientArgs["notificationId"] = positionalArgs[1];

      // Map flags
      

      
      const result = await (client as any).removeTaskNotification(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "message");
    });
}
