// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerPerspectivesCommands(program: Command, client: OmniFocusClient) {

  program.command("perspectives")
    .description("List available perspectives.")
    .alias("persp")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      

      
      const result = await (client as any).listPerspectives(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "perspective[]");
    });
}
