// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerProjectCommands(program: Command, client: OmniFocusClient) {
  const project = program.command("project").description("project commands");

  project.command("modify")
    .description("Modify project properties.")
    .alias("proj mod")
    .argument("<id>", "Project ID")
    .option("--name <string>", "Rename project")
    .option("-n, --note <string>", "Set project note")
    .option("-d, --due <date>", "Set due date")
    .option("--defer <date>", "Set defer date")
    .option("--clear-due", "Clear due date")
    .option("--clear-defer", "Clear defer date")
    .option("-f, --flag", "Flag project")
    .option("--unflag", "Unflag project")
    .option("-t, --tag <string>", "Replace tags with this single tag")
    .option("--tags <string[]>", "Replace all tags (comma-sep)")
    .option("--status <string>", "Set status (active, on-hold, done, dropped)")
    .option("--sequential", "Set to sequential")
    .option("--parallel", "Set to parallel")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      if (options.name !== undefined) clientArgs["name"] = options.name;
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.due) clientArgs["dueDate"] = parseCliDate(options.due);
      if (options.defer) clientArgs["deferDate"] = parseCliDate(options.defer);
      if (options.clearDue !== undefined) clientArgs["dueDate"] = null;
      if (options.clearDefer !== undefined) clientArgs["deferDate"] = null;
      if (options.flag !== undefined) clientArgs["flagged"] = true;
      if (options.unflag !== undefined) clientArgs["flagged"] = false;
      if (options.tag !== undefined) clientArgs["tag"] = options.tag;
      if (options.tags !== undefined) clientArgs["tags"] = parseCsv(options.tags);
      if (options.status !== undefined) clientArgs["status"] = options.status;
      if (options.sequential !== undefined) clientArgs["sequential"] = options.sequential;
      if (options.parallel !== undefined) clientArgs["sequential"] = false;

      
      const result = await (client as any).updateProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  project.command("complete")
    .description("Mark project as complete.")
    .alias("proj done")
    .argument("<id>", "Project ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).completeProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  project.command("drop")
    .description("Mark project as dropped.")
    .argument("<id>", "Project ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).dropProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  project.command("hold")
    .description("Put project on hold.")
    .alias("pause")
    .argument("<idOrName>", "Project name or ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["idOrName"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).holdProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  project.command("activate")
    .description("Resume an on-hold project.")
    .alias("resume")
    .argument("<idOrName>", "Project name or ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["idOrName"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).activateProject(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });

  project.command("review")
    .description("Mark project as reviewed.")
    .argument("<id>", "Project ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).markReviewed(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project");
    });
}
