// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerQeCommands(program: Command, client: OmniFocusClient) {

  program.command("qe")
    .description("Open Quick Entry panel.")
    .alias("quick-entry")
    .argument("[name]", "Task name")
    .option("-n, --note <string>", "Task note")
    .option("-d, --due <date>", "Due date")
    .option("--defer <date>", "Defer date")
    .option("-f, --flagged", "Mark as flagged")
    .option("--save", "Auto-save the task")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.note !== undefined) clientArgs["note"] = options.note;
      if (options.due) clientArgs["due"] = parseCliDate(options.due);
      if (options.defer) clientArgs["defer"] = parseCliDate(options.defer);
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;
      if (options.save !== undefined) clientArgs["save"] = options.save;

      
      const result = await (client as any).quickEntry(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "message");
    });
}
