// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerQuickCommands(program: Command, client: OmniFocusClient) {

  program.command("quick")
    .description("Quick add to Inbox.")
    .alias("q")
    .argument("<name>", "Task name")
    .option("-d, --due <date>", "Due date")
    .option("-f, --flagged", "Mark as flagged")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{"inbox":true} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.due) clientArgs["dueDate"] = parseCliDate(options.due);
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;

      
      const result = await (client as any).createTask(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task");
    });
}
