// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerReorderCommands(program: Command, client: OmniFocusClient) {

  program.command("reorder")
    .description("Reorder a task within its project.")
    .argument("<taskId>", "Task ID")
    .option("--top", "Move to first position")
    .option("--bottom", "Move to last position")
    .option("--before <string>", "Move before another task")
    .option("--after <string>", "Move after another task")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["taskId"] = positionalArgs[0];

      // Map flags
      if (options.top !== undefined) clientArgs["top"] = options.top;
      if (options.bottom !== undefined) clientArgs["bottom"] = options.bottom;
      if (options.before !== undefined) clientArgs["before"] = options.before;
      if (options.after !== undefined) clientArgs["after"] = options.after;

      
      const result = await (client as any).reorderTask(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task");
    });
}
