// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerReviewCommands(program: Command, client: OmniFocusClient) {

  program.command("review")
    .description("List projects due for review.")
    .option("-l, --limit <number>", "Maximum results", "50")
    .option("-a, --all", "Include all active projects")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;

      
      const result = await (client as any).getReviewQueue(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "project[]");
    });
}
