// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerSearchCommands(program: Command, client: OmniFocusClient) {

  program.command("search")
    .description("Search for tasks by name, note, or filters.")
    .alias("s")
    .argument("[query]", "Search query")
    .option("-l, --limit <number>", "Maximum results", "50")
    .option("-a, --all", "Include completed tasks")
    .option("-p, --project <string>", "Filter by project")
    .option("-t, --tag <string>", "Filter by tag")
    .option("-f, --flagged", "Only flagged tasks")
    .option("--available", "Only available tasks")
    .option("--due-before <date>", "Due before date")
    .option("--due-after <date>", "Due after date")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      clientArgs["query"] = positionalArgs[0];

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;
      if (options.project !== undefined) clientArgs["project"] = options.project;
      if (options.tag !== undefined) clientArgs["tag"] = options.tag;
      if (options.flagged !== undefined) clientArgs["flagged"] = options.flagged;
      if (options.available !== undefined) clientArgs["available"] = options.available;
      if (options.dueBefore) clientArgs["dueBefore"] = parseCliDate(options.dueBefore);
      if (options.dueAfter) clientArgs["dueAfter"] = parseCliDate(options.dueAfter);

      
      const result = await (client as any).search(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });
}
