// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function registerSummaryCommands(program: Command, client: OmniFocusClient) {

  program.command("summary")
    .description("Show a summary of the database.")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      

      // Map flags
      

      
      const result = await (client as any).getDatabaseSummary(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "summary");
    });
}
