// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerSyncCommands(program: Command, client: OmniFocusClient) {

  program.command("sync")
    .description("Synchronize the database.")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      

      // Map flags
      

      
      const result = await (client as any).sync(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "message");
    });
}
