// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate } from "../dates-cli.js";

export function registerTagCommands(program: Command, client: OmniFocusClient) {
  const tag = program.command("tag").description("tag commands");

  tag.command("tasks")
    .description("List tasks with a specific tag.")
    .alias("tag list")
    .argument("<name>", "Tag name or ID")
    .option("-l, --limit <number>", "Maximum results", "100")
    .option("-a, --all", "Include completed tasks")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.limit !== undefined) clientArgs["limit"] = options.limit;
      if (options.all !== undefined) clientArgs["all"] = options.all;

      
      const result = await (client as any).listTags(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "task[]");
    });

  tag.command("add")
    .description("Create a new tag.")
    .alias("tag create")
    .argument("<name>", "Tag name")
    .option("-p, --parent <string>", "Parent tag ID")
    .option("--no-next-action", "Disable next action")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["name"] = positionalArgs[0];

      // Map flags
      if (options.parent !== undefined) clientArgs["parent"] = options.parent;
      if (options.noNextAction !== undefined) clientArgs["no-next-action"] = options.noNextAction;

      
      const result = await (client as any).createTag(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "tag");
    });

  tag.command("modify")
    .description("Modify an existing tag.")
    .alias("tag mod")
    .argument("<id>", "Tag ID")
    .option("--name <string>", "Rename tag")
    .option("--hidden", "Hide tag")
    .option("--visible", "Show tag")
    .option("--allows-next", "Enable next action")
    .option("--no-allows-next", "Disable next action")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      if (options.name !== undefined) clientArgs["name"] = options.name;
      if (options.hidden !== undefined) clientArgs["hidden"] = options.hidden;
      if (options.visible !== undefined) clientArgs["visible"] = options.visible;
      if (options.allowsNext !== undefined) clientArgs["allows-next"] = options.allowsNext;
      if (options.noAllowsNext !== undefined) clientArgs["no-allows-next"] = options.noAllowsNext;

      
      const result = await (client as any).updateTag(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "tag");
    });

  tag.command("delete")
    .description("Delete a tag.")
    .alias("tag rm")
    .argument("<id>", "Tag ID")
    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      

      const clientArgs: any = { ...{} };
      
      // Map positional args
      clientArgs["id"] = positionalArgs[0];

      // Map flags
      

      
      const result = await (client as any).deleteTag(clientArgs);
      
      formatOutput(result, { ...program.opts(), ...options }, "message");
    });
}
