import fs from "fs";
import path from "path";
import { CLI_METADATA, CommandMeta } from "./cli-metadata.js";

const OUTPUT_DIR = "src/cli/commands";

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

export function emitCommands() {
  const groups: Record<string, CommandMeta[]> = {};

  // Group commands by their first word (e.g., "list", "add")
  for (const method of Object.values(CLI_METADATA)) {
    if (method.commands) {
      for (const cmd of method.commands) {
        const group = cmd.name.split(" ")[0];
        if (!groups[group]) groups[group] = [];
        groups[group].push(cmd);
      }
    }
  }

  for (const [group, commands] of Object.entries(groups)) {
    const content = generateGroupFile(group, commands);
    fs.writeFileSync(path.join(OUTPUT_DIR, `${group}.ts`), content);
  }

  generateIndexFile(Object.keys(groups));
}

function generateIndexFile(groups: string[]) {
  let content = `// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
`;

  for (const group of groups) {
    content += `import { register${capitalize(group)}Commands } from "./${group}.js";\n`;
  }

  content += `
export function registerAllCommands(program: Command, client: OmniFocusClient) {
`;

  for (const group of groups) {
    content += `  register${capitalize(group)}Commands(program, client);\n`;
  }

  content += `}\n`;
  fs.writeFileSync(path.join(OUTPUT_DIR, "index.ts"), content);
}

function generateGroupFile(group: string, commands: CommandMeta[]): string {
  let content = `// @generated by scripts/codegen — do not edit by hand
import { Command } from "commander";
import { OmniFocusClient } from "../../omnifocus/client.js";
import { formatOutput } from "../output.js";
import { parseCliDate, parseCsv } from "../dates-cli.js";

export function register${capitalize(group)}Commands(program: Command, client: OmniFocusClient) {
`;

  const isGroup = commands.some(c => c.name.includes(" "));
  if (isGroup) {
    content += `  const ${group} = program.command("${group}").description("${group} commands");\n`;
  }

  for (const cmd of commands) {
    const isSubcommand = cmd.name.includes(" ");
    const cmdName = isSubcommand ? cmd.name.split(" ")[1] : cmd.name;
    const parent = (isGroup && isSubcommand) ? group : "program";
    
    // If it's the base command of a group (e.g. "add" in "add" group)
    const effectiveParent = (isGroup && cmdName === group) ? group : parent;
    const effectiveCmdName = (isGroup && cmdName === group) ? "" : cmdName;

    if (effectiveCmdName === "" && isGroup) {
      // It's the base command, we configure the group object itself
      content += `
  ${group}
    .description("${cmd.description}")
`;
    } else {
      content += `
  ${effectiveParent}.command("${effectiveCmdName}")
    .description("${cmd.description}")
`;
    }

    if (cmd.aliases) {
      for (const alias of cmd.aliases) {
        content += `    .alias("${alias}")\n`;
      }
    }

    if (cmd.positional) {
      for (const pos of cmd.positional) {
        const wrap = pos.required ? ["<", ">"] : ["[", "]"];
        content += `    .argument("${wrap[0]}${pos.name}${wrap[1]}", "${pos.description}")\n`;
      }
    }

    if (cmd.flags) {
      for (const flag of cmd.flags) {
        let flagStr = "";
        if (flag.short) flagStr += `-${flag.short}, `;
        flagStr += `--${flag.long}`;
        if (flag.type !== "boolean") flagStr += ` <${flag.type}>`;
        
        let defaultValue = flag.default;
        if (defaultValue !== undefined && flag.type !== "boolean") {
          defaultValue = String(defaultValue);
        }
        
        content += `    .option("${flagStr}", "${flag.description}"${defaultValue !== undefined ? `, ${JSON.stringify(defaultValue)}` : ""})\n`;
      }
    }

    content += `    .action(async (...args) => {
      const options = args[args.length - 2];
      const command = args[args.length - 1];
      const positionalArgs = args.slice(0, args.length - 2);
      
      let stdinData = "";
      ${cmd.stdin ? `
      if (process.stdin.isTTY) {
        console.error("Error: --stdin expected but no data provided via pipe.");
        process.exit(64);
      }
      const chunks = [];
      for await (const chunk of process.stdin) chunks.push(chunk);
      stdinData = Buffer.concat(chunks).toString();
      ` : ""}

      const clientArgs: any = { ...${JSON.stringify(cmd.bindArgs || {})} };
      // Resolve relative-date bindArgs (e.g. dueBefore: "today") at runtime.
      for (const __k of Object.keys(clientArgs)) {
        if (typeof clientArgs[__k] === "string" && /^(today|tomorrow|next week|[+-]\\d+[dwmy])$/.test(clientArgs[__k])) {
          clientArgs[__k] = parseCliDate(clientArgs[__k]);
        }
      }

      // Map positional args
      ${cmd.positional?.map((pos, i) => {
        if (pos.name.endsWith("...")) {
          // Commander passes a variadic <ids...> as a single array argument,
          // so it is positionalArgs[i] — NOT positionalArgs.slice(i), which
          // would wrap it into a nested array and break every id-list command.
          return `clientArgs["${pos.name.replace("...", "")}"] = positionalArgs[${i}];`;
        }
        return `clientArgs["${pos.name}"] = positionalArgs[${i}];`;
      }).join("\n      ") || ""}

      // Map flags
      ${cmd.flags?.map(flag => {
        const camelName = flag.long.replace(/-([a-z])/g, g => g[1].toUpperCase());
        const key = JSON.stringify(flag.argKey ?? flag.long);
        // Boolean flags with a fixed bindValue (e.g. --unflag → flagged:false, --clear-due → dueDate:null)
        if (flag.bindValue !== undefined) {
          return `if (options.${camelName} !== undefined) clientArgs[${key}] = ${JSON.stringify(flag.bindValue)};`;
        }
        if (flag.type === "date") {
          return `if (options.${camelName}) clientArgs[${key}] = parseCliDate(options.${camelName});`;
        }
        if (flag.parser === "parseCsv") {
          return `if (options.${camelName} !== undefined) clientArgs[${key}] = parseCsv(options.${camelName});`;
        }
        if (flag.parser === "parseInt") {
          return `if (options.${camelName} !== undefined) clientArgs[${key}] = parseInt(options.${camelName}, 10);`;
        }
        return `if (options.${camelName} !== undefined) clientArgs[${key}] = options.${camelName};`;
      }).join("\n      ") || ""}

      ${cmd.name === "add batch" ? `
      const { parseOutline } = await import("../outline.js");
      const items = parseOutline(stdinData);
      const result = await client.batchCreateTasks({ tasks: items, ...clientArgs });
      ` : (cmd.positional?.some(p => p.name.endsWith("...")) ? `
      const ids = clientArgs["${cmd.positional.find(p => p.name.endsWith("..."))!.name.replace("...", "")}"];
      const results = [];
      for (const id of ids) {
        const singleArgs = { ...clientArgs, id };
        delete (singleArgs as any)["ids"];
        results.push(await (client as any).${getMethodNameForCommand(cmd)}(singleArgs));
      }
      const result = results.length === 1 ? results[0] : { success: true, message: \`Processed \${results.length} items\` };
      ` : `
      const result = await (client as any).${getMethodNameForCommand(cmd)}(clientArgs);
      `)}
      formatOutput(result, { ...program.opts(), ...options }, "${cmd.outputShape}");
    });
`;
  }

  content += `}\n`;
  return content;
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function getMethodNameForCommand(cmd: CommandMeta): string {
  for (const [methodName, meta] of Object.entries(CLI_METADATA)) {
    if (meta.commands?.includes(cmd)) return methodName;
  }
  return "unknown";
}
